version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "8081:80"
    networks:
      - internal
    volumes:
      - ./src/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
  php:
    build:
      context: php/
    networks:
      - internal
    volumes:
      - ./src/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
networks:
  internal:
    driver: bridge