title: Home Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            type: textarea
            size: huge
          test:
            type: layout
            layouts:
              - "1/1"
              - "1/2, 1/2"
              - "1/4, 1/4, 1/4, 1/4"
              - "1/1, 1/3, 2/3"
              - "1/1, 2/3, 1/3"
              - "1/2, 1/2, 1/3, 1/3, 1/3"
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files

