title: Careful Digital

columns:
  - width: 1/1
    sections:
      info:
        type: info
        label: info
        text:
          Welcome to the Careful Digital content management system.  Add and edit Pages from the panel below.
      pages:
        label: Pages
        type: pages
        layout: cards
        templates:
          - home
          - guides-home

